config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'

  resource :inbox
  resource :feed
  resource :spacetime
  resources :entities
  resources :isbn
  resources :http
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/http_controller.rb
class HttpController < ApplicationController
end

app/controllers/inboxes_controller.rb
class InboxesController < ApplicationController
end

app/controllers/isbn_controller.rb
class IsbnController < ApplicationController
end

app/controllers/spacetimes_controller.rb
class SpacetimesController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entities/_form.html.erb
<%= form_with(model: entity, local: true) do |form| %>
  <% if entity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
      <% entity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/entities/edit.html.erb
<h1>Editing Entity</h1>

<%= render 'form', entity: @entity %>

<%= link_to 'Show', @entity %> |
<%= link_to 'Back', entities_path %>

app/views/entities/index.html.erb
<h1>Entities</h1>

<a href="/">Home</a>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  </tbody>
</table>

<br>

<%= link_to 'New Entity', new_entity_path %>

app/views/entities/new.html.erb
<h1>New Entity</h1>

<%= render 'form', entity: @entity %>

<%= link_to 'Back', entities_path %>

app/views/entities/show.html.erb
<h1>Entity</h1>

<p id="notice"><%= notice %></p>

<a href="/">Home</a>
<a href="/entities">Entities</a>

<%= link_to 'Edit', edit_entity_path(@entity) %> |
<%= link_to 'Back', entities_path %>

app/views/feeds/show.html.erb
<h1>Feed</h1>

<a href="/">Home</a>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  </tbody>
</table>

app/views/http/index.html.erb
<h1>HTTP</h1>

<a href="/">Home</a>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  </tbody>
</table>

app/views/http/show.html.erb
<h1>HTTP</h1>

<a href="/">Home</a>
<a href="/">URLs</a>

app/views/inboxes/show.html.erb
<h1>Inbox</h1>

<a href="/">Home</a>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  </tbody>
</table>

app/views/isbn/index.html.erb
<h1>ISBNs</h1>

<a href="/">Home</a>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  </tbody>
</table>

app/views/isbn/show.html.erb
<h1>ISBN</h1>

<a href="/">Home</a>
<a href="/isbn">ISBN</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cyberpomp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/spacetimes/show.html.erb
<h1>Spacetime</h1>

<a href="/">Home</a>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  </tbody>
</table>

app/views/welcome/index.html.erb
<h1>Cyberpomp</h1>

<ul>
  <li><a href='/inbox'>Inbox</a></li>
  <li><a href='/feed'>Feed</a></li>
  <li><a href='/spacetime'>Spacetime</a></li>
  <li><a href='/entities'>Entities</a></li>
  <li><a href='/isbn'>ISBN</a></li>
  <li><a href='/http'>HTTP</a></li>
</ul>